[package]
name = "bitmask-core"
version = "0.4.0-beta.1"
authors = [
    "Jose D Robles <jd.robles@gmail.com>",
    "Hunter Trujillo <cryptoquick@pm.me>",
]
description = "Core functionality for the BitMask wallet"
edition = "2021"
license = "MIT"
homepage = "https://bitmask.app"
repository = "https://github.com/rgb-products/bitmask-core"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bitmaskd"
required-features = ["server"]

[features]
default = []
sqlite = []
web = []
server = ["tokio/full", "tower-http/cors"]

[dependencies]
anyhow = "1.0"
base64 = { package = "base64-compat", version = "1.0" }
bech32 = "0.9"
bip39 = "1.0"
bitcoin = "0.28.1"
bitcoin_hashes = "0.10.0"
console_error_panic_hook = "0.1"
directories = "4.0"
futures = "0.3"
getrandom = { version = "0.2.3", features = ["js"] }
hex = "0.4"
lazy_static = "1.4"
log = "0.4"
once_cell = "1.9"
regex = "1"
serde = "1"
serde_json = "1"
serde-encrypt = "0.7"
tokio = { version = "1", features = ["macros", "sync"] }
pretty_env_logger = "0.4"
reqwest = { version = "0.11", features = ["json"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bdk = { version = "0.23", features = [
    "use-esplora-async",
    "async-interface",
], default-features = false }
gloo-console = "0.2"
gloo-net = "0.2"
js-sys = "0.3"
# psbt = { version = "0.8.5", features = ["miniscript", "serde"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
rand = { version = "0.6", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
amplify = "3.13.0"
axum = "0.5"
axum-macros = "0.2.3"
bdk = { version = "0.23", features = [
    "use-esplora-async",
    "async-interface",
    "reqwest-default-tls",
    "sqlite-bundled",
], default-features = false }
bp-core = { version = "0.8.0", features = ["wallet"] }
carbonado = "0.1.1"
commit_verify = { version = "0.8.0", features = ["rand"] }
descriptor-wallet = { version = "0.8.3", features = ["descriptors", "serde"] }
deflate = { version = "1.0.0" }
inflate = { version = "0.4.5" }
electrum-client = "0.10.1"
lnpbp = { version = "0.8.0", features = ["all"] }
psbt = { version = "0.8.5", features = ["sign", "miniscript", "serde"] }
rgb-core = { package = "rgb-core", version = "0.8.0", features = ["serde"] }
rgb-std = { package = "rgb-std", version = "0.8.0", features = [
    "serde",
    "wallet",
] }
rgb20 = { version = "0.8.0-rc.4", features = ["serde"] }
stens = { version = "0.7.1", features = ["serde"] }
storm-core = "0.8.0"
strict_encoding = { version = "0.8.1", features = [
    "crypto",
    "chrono",
    "bitcoin",
] }
tower-http = { version = "0.3", features = ["cors"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }
