[package]
name = "bitmask-core"
version = "0.4.3"
authors = [
    "Jose Diego Robles <jose@diba.io>",
    "Hunter Trujillo <hunter@diba.io>",
    "Francisco Calderón <francisco@diba.io>",
]
description = "Core functionality for the BitMask wallet"
edition = "2021"
license = "MIT"
homepage = "https://bitmask.app"
repository = "https://github.com/diba-io/bitmask-core"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bitmaskd"
required-features = ["server"]

[features]
all = []
default = []
sqlite = []
web = []
server = ["tokio/full", "tower-http/cors"]

[dependencies]
anyhow = "1.0"
base64 = { package = "base64-compat", version = "1.0" }
bech32 = "0.9"
bip39 = "1.0"
bitcoin = { version= "0.28.1", features=["base64"] }
bitcoin_hashes = "0.10.0"
console_error_panic_hook = "0.1"
directories = "4.0"
futures = "0.3"
getrandom = { version = "0.2.3", features = ["js"] }
hex = "0.4"
lazy_static = "1.4"
log = "0.4"
once_cell = "1.9"
regex = "1"
serde = "1"
serde_json = "1"
serde-encrypt = "0.7"
tokio = { version = "1", features = ["macros", "sync"] }
pretty_env_logger = "0.4"
reqwest = { version = "0.11", features = ["json"] }
lightning-invoice = "0.20.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bdk = { version = "0.23", features = [
    "use-esplora-async",
    "async-interface",
], default-features = false }
gloo-console = "0.2"
gloo-net = "0.2"
js-sys = "0.3"
# psbt = { version = "0.8.5", features = ["miniscript", "serde"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
rand = { version = "0.6", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
amplify = "3.13.0"
axum = "0.5"
axum-macros = "0.2.3"
bdk = { version = "0.23", features = [
    "use-esplora-async",
    "async-interface",
    "reqwest-default-tls",
    "sqlite-bundled",
], default-features = false }
bitcoin_scripts = "0.8.2"
bp-core = { version = "0.8.1", features = ["psbt", "wallet"] }
bp-dbc = { version = "0.8.1", features = ["wallet"] }
carbonado = "0.1.1"
commit_verify = { version = "0.8.2", features = ["rand"] }
# commit_verify = { version = "0.9.0", features = [
#     "rand",
# ], git = "https://github.com/LNP-BP/client_side_validation.git", branch = "bitcoin-0.29" }
descriptor-wallet = {version = "0.8.3", features = ["descriptors", "serde"] }
deflate = { version = "1.0.0" }
inflate = { version = "0.4.5" }
electrum-client = "=0.10.2"
lnpbp = "0.8.0"
psbt = { version = "0.8.5", features = ["sign", "miniscript", "serde"] }
rgb_core = { package = "rgb-core", version = "0.8.1", features = ["serde"] }
rgb-std = { package = "rgb-std", version = "0.8.1", features = [
    "serde",
    "wallet",
] }
rgb20 = { version = "0.8.0", features = ["serde"] }
stens = { version = "0.7.1", features = ["serde"] }
storm-core = "0.8.0"
strict_encoding = { version = "0.8.1", features = [
    "crypto",
    "chrono",
    "bitcoin",
] }
tower-http = { version = "0.3", features = ["cors"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }

# TODO: Remove this after new descriptor wallet is released.
[patch.crates-io]
psbt = {  version = "0.8.5", git = "https://github.com/crisdut/descriptor-wallet.git", branch = "feat/tapret-desc" }
bitcoin_scripts = {  version = "0.8.2", git = "https://github.com/crisdut/descriptor-wallet.git", branch = "feat/tapret-desc" }
descriptors = {  version = "0.8.0", git = "https://github.com/crisdut/descriptor-wallet.git", branch = "feat/tapret-desc" }
bitcoin_hd = {  version = "0.8.2", git = "https://github.com/crisdut/descriptor-wallet.git", branch = "feat/tapret-desc" }