[package]
name = "bitmask-core"
version = "0.5.2"
authors = [
    "Jose Diego Robles <jose@diba.io>",
    "Hunter Trujillo <hunter@diba.io>",
    "Francisco Calderón <francisco@diba.io>",
]
description = "Core functionality for the BitMask wallet"
edition = "2021"
license = "MIT"
homepage = "https://bitmask.app"
repository = "https://github.com/diba-io/bitmask-core"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "bitmaskd"
required-features = ["server"]

[features]
all = []
default = []
web = []
server = ["tokio/full", "tower-http/cors"]

[dependencies]
anyhow = "1.0.68"
aluvm = "0.10.0"
amplify = "4.0.0"
base64 = { package = "base64-compat", version = "1.0.0" }
bech32 = "0.9.1"
bip39 = "1.0.1"
bitcoin_30 = { package = "bitcoin", version = "0.30", features = ["base64"] }
bitcoin = { version = "0.29.2", features = ["base64"] }
bitcoin_hashes = "0.11.0"
bitcoin_scripts = "0.10.0-alpha.2"
bitcoin_blockchain = "0.10.0-alpha.2"
bp-core = "0.10.0"
bp-seals = "0.10.0"
console_error_panic_hook = "0.1.7"
# directories = "4.0.1"
descriptor-wallet = { version = "0.10.0-alpha.2", features = [
    "descriptors",
    "serde",
    "miniscript",
] }
futures = "0.3.25"
getrandom = { version = "0.2.8", features = ["js"] }
hex = "0.4.3"
lightning-invoice = "0.21.0"
log = "0.4.17"
miniscript_crate = { package = "miniscript", version = "9.0.0" }
once_cell = "1.17.0"
payjoin = { version = "0.6.0", features = ["sender"] }
pretty_env_logger = "0.4.0"
psbt = { version = "0.10.0-alpha.2", features = [
    "sign",
    "miniscript",
    "serde",
    "construct",
] }
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["json"] }
rgb-std = { version = "0.10.0" }
rgb-wallet = { version = "0.10.0" }
serde = "1.0.152"
serde_json = "1.0.91"
serde-encrypt = "0.7.0"
strict_types = "1.0.0"
strict_encoding = "2.0.1"
tokio = { version = "1.27.0", features = ["macros", "sync"] }


[target.'cfg(target_arch = "wasm32")'.dependencies]
bdk = { version = "0.27.1", features = [
    "use-esplora-async",
    "async-interface",
], default-features = false }
gloo-console = "0.2.3"
gloo-net = "0.2.6"
js-sys = "0.3.61"
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.34"
web-sys = "0.3.61"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
amplify_legacy = { package = "amplify", version = "3.13.0" }
axum = "0.6.1"
axum-macros = "0.3.0"
bdk = { version = "0.27.1", features = [
    "use-esplora-async",
    "async-interface",
    "reqwest-default-tls",
], default-features = false }
bitcoin_scripts_legacy = { package = "bitcoin_scripts", version = "0.9.0" }
bp_legacy = { package = "bp-core", version = "0.9.0", features = [
    "psbt",
    "wallet",
] }
bp_dbc = { package = "bp-dbc", version = "0.9.0", features = ["wallet"] }
commit_verify = { version = "0.9.0", features = ["rand"] }
descriptor_wallet_legacy = { package = "descriptor-wallet", version = "0.9.0", features = [
    "descriptors",
    "serde",
    "miniscript",
] }
deflate = "1.0.0"
electrum_client_legacy = { version = "0.12.1", package = "electrum-client" }
inflate = "0.4.5"
lnpbp = "0.9.0"
psbt_legacy = { package = "psbt", version = "0.9.0", features = [
    "sign",
    "miniscript",
    "serde",
    "construct",
] }
rgb_core = { package = "rgb-core", version = "0.9.0" }
rgb_std = { package = "rgb-std", version = "0.9.0" }
rgb20 = { version = "0.9.0", features = ["serde"] }
stens = { version = "0.9.0", features = ["serde"] }
storm-core = "0.9.0"
strict_encoding_legacy = { package = "strict_encoding", version = "0.9.0", features = [
    "crypto",
    "chrono",
    "bitcoin",
] }
tower-http = { version = "0.3.5", features = ["cors"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.27.0", features = ["full"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

[patch.crates-io]
# TODO: Remove this after merge and release a new version
bp-dbc = { git = "https://github.com/crisdut/bp-core", branch = "feat/push_num_1" }
bp-primitives = { git = "https://github.com/crisdut/bp-core", branch = "feat/push_num_1" }
bitcoin_scripts = { git = "https://github.com/crisdut/bp-foundation", branch = "release/0.10.0-alpha.2" }
bitcoin_blockchain = { git = "https://github.com/crisdut/bp-foundation", branch = "release/0.10.0-alpha.2" }
descriptor-wallet = { git = "https://github.com/crisdut/descriptor-wallet", branch = "release/0.10.0-alpha.2" }
psbt = { git = "https://github.com/crisdut/descriptor-wallet", branch = "release/0.10.0-alpha.2" }
